# Generated by Django 5.1.5 on 2025-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
